#!/bin/bash

HELPSTRING="srm is a safe removal tool so that files can be recovered after they are deleted\n
Usage: srm <options> <file>\n
options:\n
    -h : help:print the help for srm\n
    -c : clean:remove all files in the trash\n
    -d : delete:delete a file in the trash forever\n
    -s : save:recover a file from the trash and bring it to current directory\n\n
    By: Avuxo"

if [ ! -d "$HOME/.srm" ]; then # make sure that the srm directory exists
    mkdir ~/.srm
fi

if [ "$1" == "" ]; then # make sure that the user supplied an argument
    echo "ERROR: srm requires 2 arguments"
    exit 1
fi


case $1 in
    "-c") echo "Clearing srm trash"; rm -rf $HOME/.srm/* ;;
    "-d") if [ $# -gt 1 ]; then  rm -rf $HOME/.srm/$2; fi ;;
    "-h") echo -e $HELPSTRING ;;
    "-s") if [ $# -gt 1 ]; then mv $HOME/.srm/$2 .; fi ;;
    *) if [[ $1 =~ -. ]]; then echo "Unknown command ${1}, use -h to get help"; else mv $1 $HOME/.srm; fi ;;

esac
